### ISSUE TITLE
测试了，可以用！能不能把项目名称改成“视频号下载工具”方便大家搜索

### ISSUE THREAD

**Issue by Toweo** [putyy/res-downloader#1]
测试了，可以用！能不能把项目名称改成“视频号下载工具”方便大家搜索

**Comment by putyy** [comment]
项目名称这个没必要改，因为这个软件不只是专为微信视频号而诞生，更多的是解决很多小白用户在网络上下载需要的资源，我把项目描述改了下，github上能搜出来
