### ISSUE TITLE
目前没有移动端，是否有办法能通过让手机连接电脑的热点进行抓视频呀

### ISSUE THREAD

**Issue by zhengkejie** [putyy/res-downloader#103]
目前没有移动端，是否有办法能通过让手机连接电脑的热点进行抓视频呀

**Comment by putyy** [comment]
> 目前没有移动端，是否有办法能通过让手机连接电脑的热点进行抓视频呀
移动端安装证书  手机和电脑保持同一网络 是可以的，但是移动端很多限制

**Comment by zhengkejie** [comment]
请问一下，具体要怎么生成证书并安装呀
