### ISSUE TITLE
无法下载视频号的视频，打开本软件视频号直接无法加载

### ISSUE THREAD

**Issue by chatGPT-AI-API** [putyy/res-downloader#104]

**Comment by putyy** [comment]
> _No description provided._

这不是无法下载 可能是软件没有正常运行 还有最新版需要在左上角手动打开拦截

**Comment by iseeyo** [comment]
> > _No description provided._
> 
> 这不是无法下载 可能是软件没有正常运行 还有最新版需要在左上角手动打开拦截

手动“启动代理”后，视频号页面直接变成“无法访问此网站”了……

**Comment by seadogbest** [comment]
aria2RpcClient err: TypeError: Cannot read properties of undefined (reading 'length')
    at _F.calculateDownloadProgress (D:\wechatdownload\res-downloader\resources\app.asar\dist-electron\main\index.js:22:14458)
    at D:\wechatdownload\res-downloader\resources\app.asar\dist-electron\main\index.js:29:2630
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
    微信视频号报错的日志 捕获到了 但是解析下载失败
