### ISSUE TITLE
有些微信PC版能看的视频连接，能嗅探到mp4的url，但是下载失败。下载次数限制？能不能增加一个模式：第一次嗅探的时候就直接缓存起来

### ISSUE THREAD

**Issue by EdooPlus** [putyy/res-downloader#107]
有些微信PC版能看的视频连接，能嗅探到mp4的url，但是下载失败。
比如附件这个二维码，微信扫后，发送到PC微信打开，能嗅探到mp4的url，
http://1300904305.vod2.myqcloud.com/989f3abbvodcq1300904305/8191fa7f243791581760935965/cpA2RRCDYFcA.mp4?t=673f66f9&us=652EC6B39A&sign=4d95d34405ec7054141a08be97f45a66
但是res-downloader 2.2.0 下载会报错 （仅提示下载错误）。
(2.1.2或浏览器会报错the source host is forbidden)
是不是url有下载次数限制？能不能增加一个模式：第一次嗅探的时候就直接缓存起来？ 谢谢~

![111111](https://github.com/user-attachments/assets/f74a1492-ce29-4477-94a5-4e395e8ae633)

**Comment by putyy** [comment]
> 有些微信PC版能看的视频连接，能嗅探到mp4的url，但是下载失败。 比如附件这个二维码，微信扫后，发送到PC微信打开，能嗅探到mp4的url， http://1300904305.vod2.myqcloud.com/989f3abbvodcq1300904305/8191fa7f243791581760935965/cpA2RRCDYFcA.mp4?t=673f66f9&us=652EC6B39A&sign=4d95d34405ec7054141a08be97f45a66 但是res-downloader 2.2.0 下载会报错 （仅提示下载错误）。 (2.1.2或浏览器会报错the source host is forbidden) 是不是url有下载次数限制？能不能增加一个模式：第一次嗅探的时候就直接缓存起来？ 谢谢~
> 
> ![111111](https://private-user-images.githubusercontent.com/103444854/388575859-f74a1492-ce29-4477-94a5-4e395e8ae633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2Njg1MDksIm5iZiI6MTczMjY2ODIwOSwicGF0aCI6Ii8xMDM0NDQ4NTQvMzg4NTc1ODU5LWY3NGExNDkyLWNlMjktNDQ3Ny05NGE1LTRlMzk1ZThhZTYzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMDQzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjM4MmMyMTlkYTgwZmU1NzJhOTMzMWU3M2VjMzlkYmQwYTA4MTNiOTk2MjZmYjAyNjVjNzgxOWI0NmU5YWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rdTYdMIvWa8CkrezHfviqyODMK8aV1LcsskgP3w7xVs)

大部分资源链接都会有时效 缓存没用的
