### ISSUE TITLE
怎么安装证书啊？现在一打开就提示删除

### ISSUE THREAD

**Issue by kissingdrer** [putyy/res-downloader#110]
说明第一步要安装证书？
证书在哪里啊，怎么安装啊，感谢各位大神

**Comment by putyy** [comment]
win系统正常情况会自动安装 mac需要执行命令安装。命令会自动复制到剪切板

**Comment by tiantian0122** [comment]
> 说明第一步要安装证书？ 证书在哪里啊，怎么安装啊，感谢各位大神

跟你有同样的问题，打开直接提示已损坏，移除废纸篓。解决办法，复制下面，粘贴到终端运行，就行
sudo xattr -dr com.apple.quarantine /Applications/res-downloader.app
