### ISSUE TITLE
无法定位程序输入点 DiscardvirtualMemory 于动态链接库KERNEL32.. 上。

### ISSUE THREAD

**Issue by hhhaiai** [putyy/res-downloader#113]
<img width="371" alt="image" src="https://github.com/user-attachments/assets/e2d32ddf-298c-41da-9279-7b4205bf5669">

**Comment by putyy** [comment]
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/5738285/391874213-e2d32ddf-298c-41da-9279-7b4205bf5669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDA2NzAsIm5iZiI6MTczMzMwMDM3MCwicGF0aCI6Ii81NzM4Mjg1LzM5MTg3NDIxMy1lMmQzMmRkZi0yOThjLTQxZGEtOTI3OS03YjQyMDViZjU2NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDgxOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE2YzRjNWYzZmE4NWUwMmU1ZDcyNmQ4NzI4ZWQwNjRjZDE0NjViYjUwZDc3NDQxZjQ2N2NkZDU5ZWMwOTdkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.t-xRIoHMRyCjl8-Cu1HZ-OiyeMPpFea1B3Ae_Q6ZLKQ">

试试2.3.0最新版

**Comment by hhhaiai** [comment]
Ok
