### ISSUE TITLE
微信视频号下载失败

### ISSUE THREAD

**Issue by moexizer** [putyy/res-downloader#115]
版本号 Windows 2.3.0 ，已安装证书开启代理，设置好了下载路径，可以抓取到视频但无法预览，点击解密下载立即提示下载失败，没有错误信息。

**Comment by putyy** [comment]
> 版本号 Windows 2.3.0 ，已安装证书开启代理，设置好了下载路径，可以抓取到视频但无法预览，点击解密下载立即提示下载失败，没有错误信息。

可能安装是没有允许aria2网络访问 可以复制链接用其他工具下载
