### ISSUE TITLE
微信视频号部分视频可以下载，部分卡死

### ISSUE THREAD

**Issue by orange-patrick** [putyy/res-downloader#116]
这个视频可以下载
`https://finder.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQDs4sRuHgbpTQ8DzRicNsSbpMmEsSwqtL8RgjJcqZ8K7CBjGE9Sp5QIBGSiao0IlKhvcP9npHyiaXg4p0pWyZbcacO&bizid=1023&dotrans=0&hy=SH&idx=1&m=&uzid=1&token=cztXnd9GyrHUjGpndS68rIrLYh1MVk6dN6zjPQCK1DhvdDvXkDBM7ibWnic7W3YKx5JwkGL61HRl2aP7Fz7pJPCC8M3Fhu1HJ75GaPxqNUtKksbu7tRbuxXuz9SY1JyXmj&basedata=CAASABoGeFdUMTExGgZ4V1QxMTIaBnhXVDExMxoGeFdUMTU2GgZ4V1QxNTcaBnhXVDE1OCIA&sign=VWuNAalJtrlb9ItU0Iv0RWc5a2J4ltnBhS2eGpjd1Ka-OS4yAcovSW80y5W7wdn58VpFb2OMtCRlUL66o5dfQA&ctsc=143&web=1&extg=10f0000&svrbypass=AAuL%2FQsFAAABAAAAAAA%2BuZf2e1y9dm1IM%2B5XZxAAAADnaHZTnGbFfAj9RgZXfw6VMdpwbfpaH7Hc7MehaPNvzazjdTScxZp8DHVTs9xjU%2Fj54lx7LpDCTWc%3D&svrnonce=1733815859`

这个视频不行，百分比一直不变，截图如下
`https://finder.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eewK0tHtibORqcsqchXNh0Gf3sJcaYqC2rQATQxDBiayiaJBTs3l7ynEluBIKB4QPzttw5YrktBiapvdZVe9cIc62AYxm2LH85Udnk5dibY7E6EicnaL8dtsUcN4fZ&bizid=1023&dotrans=0&hy=SH&idx=1&m=&uzid=1&token=cztXnd9GyrHUjGpndS68rIrLYh1MVk6d8ZaPPibicKjFf4oRakWCE6oOkSqDp1hb6ruKsObDiaGfbMU4aYeEibsAkfp64U6ZSictFHsbt1eXw6jLiat6zJhkZaic3W1UI5VSOwM&basedata=CAASABoGeFdUMTExGgZ4V1QxMTIaBnhXVDExMxoGeFdUMTU2GgZ4V1QxNTcaBnhXVDE1OCIA&sign=ORLk6z3lOyBrdFXrTms7Tg4v-DcserxtYLx61iwZt58H_7dH2yzs3mZMAV8cjRnAaXugozX1J1r9ekYsc7pZaA&ctsc=143&web=1&extg=10f0000&svrbypass=AAuL%2FQsFAAABAAAAAAD9bzTWJKMUrc%2FqM%2B5XZxAAAADnaHZTnGbFfAj9RgZXfw6VMdpwbfpaH87cgI7AQ%2BBrzazjdTScxZp8DH7LVTFLKisVSWQpX6KCVYg%3D&svrnonce=1733815859`

![screenshot-20241210-161836](https://github.com/user-attachments/assets/99d5d370-ce97-4e9a-84c7-e5ce325204e7)

**Comment by putyy** [comment]
@orange-patrick 下最新版
