### ISSUE TITLE
mac 版本，视频下载后不能播放，没看到有解密的按钮，我什么姿势没对？

### ISSUE THREAD

**Issue by songyunbiao** [putyy/res-downloader#12]
![WX20240111-112910@2x](https://github.com/putyy/res-downloader/assets/9216385/a191a2c2-5af8-4f07-9326-5b9a6a84dd39)

**Comment by putyy** [comment]
视频单独发给文件助手 再打开 有解密下载的才能解密

**Comment by putyy** [comment]
![Uploading image.png…]()
这样的

**Comment by putyy** [comment]
![image](https://github.com/putyy/res-downloader/assets/31536789/700aefa9-9f70-4a7c-9303-01f0b2845c9f)
z这样的

**Comment by songyunbiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/31536789/295782268-700aefa9-9f70-4a7c-9303-01f0b2845c9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTM2NDIsIm5iZiI6MTcwNDk1MzM0MiwicGF0aCI6Ii8zMTUzNjc4OS8yOTU3ODIyNjgtNzAwYWVmYTktOWY3MC00YTdjLTkzMDMtMDFmMGIyODQ1YzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzlmMzhmYmExOTMzNzBhYTI4MmNhOGM1MzM4NjMwMTE2M2MwODMyNzMwZjZlNzc1MzI2Njg1Mzc4ODQwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dyNZ-EXDPFm_VEgll0Eex0CZ6oGTcM_h_orr4ZKHHhg) z这样的

原来这个样子，看来是我打开的姿势没对。
