### ISSUE TITLE
代理服务器冲突

### ISSUE THREAD

**Issue by Tairraos** [putyy/res-downloader#13]
clash也是使用本机代理进行科学上网的。 

嗅探器能否在启动时读出系统代理，然后8899不仅抓包，请求使用启动时的代理设置，如此可抓取utube视频。
退出时再恢复之前的系统代理。

如果启动时系统代理为关，则使用当前的逻辑没问题。

谢谢。

另外，能不能做一下美化?
比如：主机地址可以做一个美化处理，这样就不会。常见的视频地址换成图标显示。比如微信，b站，youtube。不知道的地址换用一个地球图标。
操作也可以换成4个图标。图标可以使用 [iconify](https://icon-sets.iconify.design/), npm装个包就可以引用。

谢谢谢谢。

**Comment by weavers1f** [comment]
好像启动这个软件的时候，clash是不是用不了，关掉后也是要过一段时间才能重新能用clash

**Comment by Tairraos** [comment]
那是因为clash是修改系统的代理，把代理设置成 127.0.0.1:7890
这个软件也是修改系统的代理，把代理设置成 127.0.0.1:8899
clash和这个软件关掉的时候，都会做一个动作，把系统代理设置成空

所以，它并不是关掉后要过一段时间才能使用clash，而是，关掉后直到你手动开关一次clash，clash都不能使用了。
或者你在开着软件的时候，退出clash，clash把代理清空，这个软件也抓不到包了。

**Comment by Tairraos** [comment]
软件启动的时候，发现有系统代理，那只要软件的请求都向系统代理发送就可以了。

相当于，请求 -> 127.0.0.1:8899 -> 127.0.0.1:7890 -> target

**Comment by putyy** [comment]
1楼的说法 理论是可行的 最近暂时没时间来做这个尝试，
2楼的情况 启动本软件 clash 无法使用，因为系统代理被更改，关闭该软件 重新设置下clash(关闭代理 打开代理)即可

**Comment by weavers1f** [comment]
> 那是因为clash是修改系统的代理，把代理设置成 127.0.0.1:7890 这个软件也是修改系统的代理，把代理设置成 127.0.0.1:8899 clash和这个软件关掉的时候，都会做一个动作，把系统代理设置成空
> 
> 所以，它并不是关掉后要过一段时间才能使用clash，而是，关掉后直到你手动开关一次clash，clash都不能使用了。 或者你在开着软件的时候，退出clash，clash把代理清空，这个软件也抓不到包了。

原来如此，感谢解惑。
