### ISSUE TITLE
视频号上的视频能下载，但无法播放

### ISSUE THREAD

**Issue by hyzhzz** [putyy/res-downloader#14]
视频号上的视频能下载，但无法播放，下载下来的格式为.mp4，但是不管用什么播放器都播放不了，比如Pot Player等

**Comment by putyy** [comment]
> 视频号上的视频能下载，但无法播放，下载下来的格式为.mp4，但是不管用什么播放器都播放不了，比如Pot Player等

@hyzhzz 看这里 #15
