### ISSUE TITLE
工具软件与视频号都打开后没有发现视频与正在播放的视频

### ISSUE THREAD

**Issue by ljyww83** [putyy/res-downloader#16]
工具软件与视频号都打开后没有发现视频与正在播放的视频
<img width="935" alt="企业微信截图_17063314692142" src="https://github.com/putyy/res-downloader/assets/44224796/b5bc8ff5-cafe-4fe8-b688-42cd3c237890">
<img width="935" alt="企业微信截图_17063314692142" src="https://github.com/putyy/res-downloader/assets/44224796/70f79e58-30e5-42c7-8be1-01c24cac484e">

**Comment by putyy** [comment]
估计是代理没有设置好 手动设置下 @ljyww83
