### ISSUE TITLE
不知道为什么我一开代理就是无法上网

### ISSUE THREAD

**Issue by qzwl** [putyy/res-downloader#18]
很奇怪。

**Comment by putyy** [comment]
> 很奇怪。

mac 还是 win?

启动软件后 手动检测下代理设置

**Comment by qzwl** [comment]
Windows11 确认过 代理有的

![image](https://github.com/putyy/res-downloader/assets/20476126/10c64d9d-f663-418f-a255-f98e43d158df)

**Comment by qzwl** [comment]
只要开了 就无法上网。

**Comment by putyy** [comment]
> 只要开了 就无法上网。

oo win11 晚点我看下

**Comment by zmdljd** [comment]
我的也是，一打开软件，视频号和浏览器就无法上网

**Comment by lqllife** [comment]
> @qzwl @qzwl win11 刚刚测试是可以的，，可以试着卸载重装，确保证书安装成功、以及代理设置正确的

我试了不行，重新卸载了，证书也是安装好的，代理也是自动配置好的。
![image](https://github.com/putyy/res-downloader/assets/23254569/39f147a3-9cbf-4ba1-a4cd-571a65d41b97)

安装和使用期间还把clash退出了，现在还是不行。

**Comment by putyy** [comment]
@lqllife 
也是win11 ？

**Comment by lqllife** [comment]
> @lqllife 也是win11 ？

是的，晚上回家用win10试试。

**Comment by lqllife** [comment]
> @lqllife 也是win11 ？

我win10的电脑可以。

**Comment by putyy** [comment]
@lqllife win11下手动把用户目录下 .res-downloader@putyy 文件夹下的res-downloader-installed.lock 删掉
  重新安装: 安装时选择全部用户安装，，后面的全选是  然后再试下

**Comment by lqllife** [comment]
> @lqllife win11下手动把用户目录下 .res-downloader@putyy 文件夹下的res-downloader-installed.lock 删掉 重新安装: 安装时选择全部用户安装，，后面的全选是 然后再试下

我试了还是不行。

**Comment by Mic-ao** [comment]
win10    系统。 运行软件后，pc无法上网。 关闭软件，先打开pc端微信，打开视频号，然后打开软件。软件没有反应，此时网页也打不开了。

解决方案： 
由于我是在软路由上已经设置好了科学上网。所以，尝试不设置本软件的代理。也就是跳过这一步（代理栏  留空）。一切正常。大家参考一下

**Comment by 957374679** [comment]
我也有这个问题，这是什么情况的？之前的版本不会，现在这个版本就会

**Comment by putyy** [comment]
> 我也有这个问题，这是什么情况的？之前的版本不会，现在这个版本就会

不用软件手动关闭下代理 同样使用时无法嗅探也可手动设置下代理

**Comment by Linbin02** [comment]
@putyy 无论有没有开vpn，在打开软件后会自动打开软件代理，但在它的8899端口下不知道为什么都无法正常上网，打不开视频号。然后手动禁止软件代理的话，重新打开软件会显示Error: Error invoking remote method 'invoke_start_proxy': setting proxy err: Error: access is denied代理错误，嗅探不到视频。死循环了属于是

**Comment by putyy** [comment]
> @putyy 无论有没有开vpn，在打开软件后会自动打开软件代理，但在它的8899端口下不知道为什么都无法正常上网，打不开视频号。然后手动禁止软件代理的话，重新打开软件会显示Error: Error invoking remote method 'invoke_start_proxy': setting proxy err: Error: access is denied代理错误，嗅探不到视频。死循环了属于是

打开res-downloader自动打开其他代理软件？ res-downloader没做这个操作哦，打开软件后手动把代理设置清空，关闭代理软件，关闭res-downloader  重新再打开res-downloader 看看是否能正常拦截

**Comment by mrsteed** [comment]
我也遇到了这个问题：

**Comment by mrsteed** [comment]
我也遇到了这个问题：

**Comment by mrsteed** [comment]
WIN11的系统我也遇到了这个问题。
安装软件后打开软件，系统代理自动变为127.0.0.1:8899 但是此时浏览器无法上网。
经过多次尝试，找到了临时解决方案供参考：
1、首先有代理软件，把软件配置为全局代理，并找到软件的代理端口号比如：
![image](https://github.com/putyy/res-downloader/assets/41712427/a5ca5680-36a2-4ea8-9bab-428bb752f035)
2、然后设置软件代理端口号保持一致
![image](https://github.com/putyy/res-downloader/assets/41712427/86803af2-7ef5-41b2-8e08-7b3b95803d8f)
3、软件重启，然后就可以正常捕获了。但是此时的系统代理端口号会变成8899。
猜测应该是res-downloader8899端口的代理可能存在某些问题。

**Comment by mrsteed** [comment]
WIN11的系统我也遇到了这个问题。
安装软件后打开软件，系统代理自动变为127.0.0.1:8899 但是此时浏览器无法上网。
经过多次尝试，找到了临时解决方案供参考：
1、首先有代理软件，把软件配置为全局代理，并找到软件的代理端口号比如：
![image](https://github.com/putyy/res-downloader/assets/41712427/a5ca5680-36a2-4ea8-9bab-428bb752f035)
2、然后设置软件代理端口号保持一致
![image](https://github.com/putyy/res-downloader/assets/41712427/86803af2-7ef5-41b2-8e08-7b3b95803d8f)
3、软件重启，然后就可以正常捕获了。但是此时的系统代理端口号会变成8899。
猜测应该是res-downloader8899端口的代理可能存在某些问题。

**Comment by Linbin02** [comment]
@mrsteed 感谢，已解决

**Comment by Linbin02** [comment]
@putyy 
1. 我没讲清楚，不是打开其他软件代理，是打开res后，系统代理变为127.0.0.1:8899，然后上不了网，不过已经按mrsteed的方法解决上网问题并下载到视频了。而且后续端口也确实是变成8899，然后试图上YouTube上不了，不过正常国内上网包括视频号都可以。
2. 另外虽然能下载了，但是得先打开一个其他代理软件。在不打开其他代理软件的情况下，如何设置来嗅探视频？我将防火墙的出入站规则都对8899端口接通了还是不行。

**Comment by putyy** [comment]
> @putyy
> 
> 1. 我没讲清楚，不是打开其他软件代理，是打开res后，系统代理变为127.0.0.1:8899，然后上不了网，不过已经按mrsteed的方法解决上网问题并下载到视频了。而且后续端口也确实是变成8899，然后试图上YouTube上不了，不过正常国内上网包括视频号都可以。
> 2. 另外虽然能下载了，但是得先打开一个其他代理软件。在不打开其他代理软件的情况下，如何设置来嗅探视频？我将防火墙的出入站规则都对8899端口接通了还是不行。

没这么复杂，正常操作就是打开res  通常情况会自动设置系统代理为8899  如果这时还不行 那手动去设置一下(这里去设置其实能看到是设置好的 之前测试过有的系统会存在这个问题 手动打开设置页面就可以了) 应该就行了

要想打开国外网站 比如YouTube 就把其他代理软件打开 在res设置里面把代理设置为其他软件得代理地址，将系统代理还是设置为res 就行，，但YouTube暂时无法下载 因为他得视频做了处理 res还没进行任何适配

**Comment by xiaoxi-ctrl** [comment]
需要手动设置一下代理服务地址和端口，重启软件应该就行了。 @mrsteed 试了一下他的方法，没有用到代理软件，就解决问题了

**Comment by rainboxup** [comment]
手动改一下软件里的代理端口号就可以

**Comment by azhong0769** [comment]
真的好奇怪，不开魔法就可以，开了魔法就上不了外网

**Comment by putyy** [comment]
> 真的好奇怪，不开魔法就可以，开了魔法就上不了外网

开魔法要在软件里设置下代理

**Comment by xcdmrCHP** [comment]
我这里用7890，无论是全局还是规则，微信视频号都只加载出页面，加载不出视频。关闭后就正常了。但使用8899，则网页都打不开

**Comment by xcdmrCHP** [comment]
> 我这里用7890，无论是全局还是规则，微信视频号都只加载出页面，加载不出视频。关闭后就正常了。但使用8899，则网页都打不开 系统代理设置也看过了

后来把系统代理设置那里的禁用地址全删了，再把7890的`Allow LAN`打开，就可以了。视频号那里视频播不出来，但可以正常解密下载。

后续发现，如果视频没有标题，就无法下载，也嗅探不到
