### ISSUE TITLE
启动软件后，打开视频号提示不是隐私连接

### ISSUE THREAD

**Issue by zwjzxh520** [putyy/res-downloader#2]
<img width="777" alt="image" src="https://github.com/putyy/res-downloader/assets/2184202/2b74376e-0c7e-4112-ac61-859a5b9f11c6">

该怎么解决？

**Comment by putyy** [comment]
可能是系统代理没有设置好，你手动设置一下 127.0.0.1:8899

**Comment by zwjzxh520** [comment]
用了1.0.2后解析正常了
