### ISSUE TITLE
保存位置无法设置

### ISSUE THREAD

**Issue by fsyyk** [putyy/res-downloader#31]
在设置里面设置好保存位置之后，去下载视频，会提示要设置保存位置。点到设置里面发现保存位置不能设置，装了好几个版本，换了一个电脑都行？请问如何解决？

**Comment by iceapp520** [comment]
我也是这个问题，请问该怎么解决

**Comment by putyy** [comment]
@fsyyk @iceapp520  点击保存位置 右侧通常会拉起系统弹窗选择文件夹保存，选择后要点击下面的保存按钮，，，如果已经设置会显示当前设置的保存位置，是无法弹出系统选择框还是无法保存？

**Comment by fengziX** [comment]
> @fsyyk @iceapp520 点击保存位置 右侧通常会拉起系统弹窗选择文件夹保存，选择后要点击下面的保存按钮，，，如果已经设置会显示当前设置的保存位置，是无法弹出系统选择框还是无法保存？
![2](https://github.com/putyy/res-downloader/assets/25502192/f7a8184a-a86f-4fb2-a408-2b2f9c8c90ac)
设置完毕以后,
离开设置页面, 再切换到设置页面 , 
又会变回
![Uploading 1.png…]()
