### ISSUE TITLE
m1下载arm64版本 无法安装 提示文件已损坏

### ISSUE THREAD

**Issue by chrisoooo** [putyy/res-downloader#32]
![截屏2024-04-01 17 16 22](https://github.com/putyy/res-downloader/assets/9098297/b6c22d3c-1b65-4dc1-b04d-14385894f348)

下载非arm64版本的，偶尔可以捕获到，大部分情况下不行

**Comment by putyy** [comment]
偶尔？是否哪里操作不对呢 可以手动检测下代理是否正确设置

**Comment by caihongyu2022** [comment]
在命令行 执行以下命令，就不提示损坏了
xattr -cr +空格 + res-downloader.app 拖入进来

**Comment by ccrocc** [comment]
```shell
sudo spctl --master-disable && xattr -cr /Applications/res-downloader.app
```

**Comment by yuzerofish** [comment]
> 在命令行 执行以下命令，就不提示损坏了 xattr -cr +空格 + res-downloader.app 拖入进来

这个方法试了还是不成功,同样是m1

**Comment by yuzerofish** [comment]
> ```shell
> sudo spctl --master-disable && xattr -cr /Applications/res-downloader.app
> ```

这个方法试了也不成功
