### ISSUE TITLE
intel mac yarn install报错

### ISSUE THREAD

**Issue by crithes** [putyy/res-downloader#34]
你好，我yarn install报错：error /Users/gaojie/Desktop/flutter/oldapp/fluttercrm/res-downloader/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
我的nodejs版本是Node.js v18.0.0

**Comment by kinglee9527** [comment]
> error /Users/kinglee/Documents/funspace/res-downloader/node_modules/electron: Command failed. Exit code: 1 Command: node install.js Arguments: Directory: /Users/kinglee/Documents/funspace/res-downloader/node_modules/electron Output: RequestError: Hostname/IP does not match certificate's altnames: Host: npm.taobao.org. is not in the cert's altnames: DNS:_.tbcdn.cn, DNS:_.taobao.com, DNS:_.alicdn.com, DNS:_.cmos.greencompute.org, DNS:cmos.greencompute.org, DNS:m.intl.taobao.com, DNS:_.mobgslb.tbcache.com, DNS:_.alikunlun.com, DNS:alikunlun.com, DNS:_.django.t.taobao.com, DNS:alicdn.com, DNS:_.tbcache.com, DNS:_.tmall.com, DNS:_.1688.com, DNS:_.3c.tmall.com, DNS:_.alibaba.com, DNS:_.aliexpress.com, DNS:_.aliqin.tmall.com, DNS:_.alitrip.com, DNS:_.aliyun.com, DNS:_.cainiao.com, DNS:_.cainiao.com.cn, DNS:_.chi.taobao.com, DNS:_.chi.tmall.com, DNS:_.china.taobao.com, DNS:_.dingtalk.com, DNS:_.etao.com, DNS:_.feizhu.cn, DNS:_.feizhu.com, DNS:_.fliggy.com, DNS:_.fliggy.hk, DNS:_.food.tmall.com, DNS:_.jia.taobao.com, DNS:_.jia.tmall.com, DNS:_.ju.taobao.com, DNS:_.juhuasuan.com, DNS:_.lw.aliimg.com, DNS:_.m.1688.com, DNS:_.m.alibaba.com, DNS:_.m.alitrip.com, DNS:_.m.cainiao.com, DNS:_.m.etao.com, DNS:_.m.taobao.com, DNS:_.m.taopiaopiao.com, DNS:_.m.tmall.com, DNS:_.m.tmall.hk, DNS:_.mei.com, DNS:_.taopiaopiao.com, DNS:_.tmall.hk, DNS:_.trip.taobao.com, DNS:_.xiami.com, DNS:1688.com, DNS:alibaba.com, DNS:aliexpress.com, DNS:alitrip.com, DNS:aliyun.com, DNS:cainiao.com, DNS:cainiao.com.cn, DNS:dingtalk.com, DNS:etao.com, DNS:feizhu.cn, DNS:feizhu.com, DNS:fliggy.com, DNS:fliggy.hk, DNS:juhuasuan.com, DNS:mei.com, DNS:taobao.com, DNS:taopiaopiao.com, DNS:tmall.hk, DNS:xiami.com, DNS:tmall.com, DNS:_.cloudvideocdn.taobao.com, DNS:cloudvideocdn.taobao.com, DNS:tbcdn.cn at ClientRequest. (/Users/kinglee/Documents/funspace/res-downloader/node_modules/got/dist/source/core/index.js:970:111) at Object.onceWrapper (node:events:627:26) at ClientRequest.emit (node:events:524:35) at origin.emit (/Users/kinglee/Documents/funspace/res-downloader/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20) at TLSSocket.socketErrorListener (node:_http_client:496:9) at TLSSocket.emit (node:events:512:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) at new NodeError (node:internal/errors:399:5) at Object.checkServerIdentity (node:tls:337:12) at TLSSocket.onConnectSecure (node:_tls_wrap:1550:27)
> 
> 我也有同样的问题

mac电脑 Sonoma 14.1 node版本  v19.6.0

**Comment by kinglee9527** [comment]
cnpm install 安装成功了

**Comment by putyy** [comment]
安装不了的情况 一般情况都跟跟网络有关
设置好命令行代理 用特殊网络进行安装
同楼上 cnpm 也行
