### ISSUE TITLE
您的连接不是私密连接

### ISSUE THREAD

**Issue by mm7ty** [putyy/res-downloader#39]
打开软件后，点击分享的视频号链接显示：
您的连接不是私密连接
攻击者可能会试图从 channels.weixin.qq.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。[了解详情](chrome-error://chromewebdata/#)
NET::ERR_CERT_INVALID

**Comment by putyy** [comment]
首页顶部有没有 “安装检测(如果看到此按钮说明软件安装未完成则需要手动点击此按钮)” 提示？
