### ISSUE TITLE
请问能不能在NAS上面部署？

### ISSUE THREAD

**Issue by gegewuwuwu** [putyy/res-downloader#4]
RT
这样可以网页访问去下载些视频.

**Comment by putyy** [comment]
@gegewuwuwu 
对nas的架构不是很了解，你可以拉代码打包linux版本执行文件试试

**Comment by gegewuwuwu** [comment]
> @gegewuwuwu 对nas的架构不是很了解，你可以拉代码打包linux版本执行文件试试

主要是x86上面 linux系统docker跑，有个dockerimages 也可以的

**Comment by kokojacket** [comment]
同求个dockerfile

**Comment by fimreal** [comment]
能有个 linux 打包方式，就可以用 novnc 容器跑起来了，但是看 readme 只有 mac 和 win 的打包参数
