### ISSUE TITLE
Windows7使用不了

### ISSUE THREAD

**Issue by nosiyBUGS** [putyy/res-downloader#43]
![image](https://github.com/putyy/res-downloader/assets/34706919/31e334f8-bfaa-49f1-9135-180ab55776a1)

**Comment by putyy** [comment]
> ![image](https://private-user-images.githubusercontent.com/34706919/334623411-31e334f8-bfaa-49f1-9135-180ab55776a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTg1NzUsIm5iZiI6MTcxNzQxODI3NSwicGF0aCI6Ii8zNDcwNjkxOS8zMzQ2MjM0MTEtMzFlMzM0ZjgtYmZhYS00OWYxLTkxMzUtMTgwYWI1NTc3NmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEyMzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDQwYzU3MjVkNTM1MTU4ODEwNDljOWQ4NGM0YzE1ZDQ0MThlYzMwNjBlNWI3NzE3OTdjMWRhMmY1NTgzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSBMwZMLWEnCxwlE_Xa9bADYf5Uc2_DzI3Gi_rfzPWE)

win7是不行的

**Comment by nosiyBUGS** [comment]
能不能编译一版出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月3日(周一) 晚上10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [putyy/res-downloader] Windows7使用不了 (Issue #43)




  

  
win7是不行的

**Comment by putyy** [comment]
> 能不能编译一版出来
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月3日(周一) 晚上10:38 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [putyy/res-downloader] Windows7使用不了 (Issue #43) win7是不行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你可以自己降低下electron版本 编译下
