### ISSUE TITLE
我想问下node.js的版本是多少

### ISSUE THREAD

**Issue by Denghongyuan** [putyy/res-downloader#44]

**Comment by putyy** [comment]
> _No description provided._

最新版就行

**Comment by Denghongyuan** [comment]
![image](https://github.com/putyy/res-downloader/assets/25816587/08beadad-1d69-4c29-a277-6df4d88117d7)
能帮我看下什么情况吗？我前面执行yarn install是没有任何报错的，但是到了yarn run dev就报错了

**Comment by putyy** [comment]
> 最新版就行

什么系统？ 删掉node_modules   挂上代理用npm重新安装试试

**Comment by putyy** [comment]
> ![image](https://private-user-images.githubusercontent.com/25816587/338412782-08beadad-1d69-4c29-a277-6df4d88117d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzU3MzcsIm5iZiI6MTcxODA3NTQzNywicGF0aCI6Ii8yNTgxNjU4Ny8zMzg0MTI3ODItMDhiZWFkYWQtMWQ2OS00YzI5LWEyNzctNmRmNGQ4ODExN2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAzMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGM0YzQxODUxMTU0YzUyZTkxNDhlNjU4MTYzYzk0MWI5ZWVkYmJkNzk5OGYzMDRlN2RkM2IxZDc5NGMzYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tU7RPXmdVXssxzpUW-y9yfXmbdROU3hJyeMfQnmkPg4) 能帮我看下什么情况吗？我前面执行yarn install是没有任何报错的，但是到了yarn run dev就报错了

什么系统？ 删掉node_modules 挂上代理用npm重新安装试试

**Comment by Denghongyuan** [comment]
我是用docker运行的[alpine](node:18-alpine)容器，用的是香港服务器，应该是没有墙的问题

**Comment by putyy** [comment]
> 我是用docker运行的alpine容器，用的是香港服务器，应该是没有墙的问题

linux应该是不行的  没试过， win 或 mac 可行
