### ISSUE TITLE
视频号可以嗅探到，但是为什么抖音，小红书我试了都不行呢？

### ISSUE THREAD

**Issue by imtiger** [putyy/res-downloader#53]
视频号可以嗅探到，但是为什么抖音，小红书我试了都不行呢？

**Comment by putyy** [comment]
> 视频号可以嗅探到，但是为什么抖音，小红书我试了都不行呢？

更新到2.0

**Comment by imtiger** [comment]
> > 视频号可以嗅探到，但是为什么抖音，小红书我试了都不行呢？
> 
> 更新到2.0

我是用的最新源代码，在本地运行的，是mac系统，不知道是不是Mac的原因。

**Comment by putyy** [comment]
不行是拦截不到还是什么意思？

**Comment by putyy** [comment]
> > > 视频号可以嗅探到，但是为什么抖音，小红书我试了都不行呢？
> > 
> > 
> > 更新到2.0
> 
> 我是用的最新源代码，在本地运行的，是mac系统，不知道是不是Mac的原因。

**Comment by imtiger** [comment]
> 不行是拦截不到还是什么意思？

拦截不到请求，抖音和小红书都拦截不到，但是视频号是可以的。视频号是用的Mac 桌面版微信里打开的，抖音和小红书我是用chrome浏览器打开的。

**Comment by imtiger** [comment]
> > 不行是拦截不到还是什么意思？
> 
> 拦截不到请求，抖音和小红书都拦截不到，但是视频号是可以的。视频号是用的Mac 桌面版微信里打开的，抖音和小红书我是用chrome浏览器打开的。
我看拦截请求是在下面的代码里吧：
`proxy.intercept(
                {
                    phase: 'response',
                },
                async (req, res) => {
                    try {
                        // 拦截响应
                        const ctype = res?._data?.headers?.['content-type']
                        const url_sign: string = hexMD5(req.fullUrl())
                        const res_url = req.fullUrl()
                        const urlInfo = urlTool.parse(res_url, true)
                        switch (ctype) {
                            case "video/mp4":
                            case "video/webm":
                            case "video/ogg":
                            case "video/x-msvideo":
                            case "video/mpeg":
                            case "video/quicktime":
                            case "video/x-ms-wmv":
                            case "video/x-flv":
                            case "video/3gpp":
                            case "video/x-matroska":
                                console.log(`video url:${res_url}`)`

**Comment by putyy** [comment]
这段是根据 http content-type 统一判断资源类型的  晚点试试MAC吧！

**Comment by imtiger** [comment]
> 这段是根据 http content-type 统一判断资源类型的 晚点试试MAC吧！

抖音和小红书视频，也都是根据http content-type  嗅探的吗

**Comment by putyy** [comment]
> > 这段是根据 http content-type 统一判断资源类型的 晚点试试MAC吧！
> 
> 抖音和小红书视频，也都是根据http content-type 嗅探的吗

都是统一的 浏览器F12看下请求是否走了代理，，看请求头 Remote Address信息

**Comment by imtiger** [comment]
> > > 这段是根据 http content-type 统一判断资源类型的 晚点试试MAC吧！
> > 
> > 
> > 抖音和小红书视频，也都是根据http content-type 嗅探的吗
> 
> 都是统一的 浏览器F12看下请求是否走了代理，，看请求头 Remote Address信息

我试了下，如果是用mac 下safari浏览器是可以嗅探到的，但是用chrome和firefox浏览器不行，我chrome浏览器是最新版本：126.0.6478.183 (Official Build) (arm64) ，这种有可能是什么原因？

**Comment by imtiger** [comment]
> > > > 这段是根据 http content-type 统一判断资源类型的 晚点试试MAC吧！
> > > 
> > > 
> > > 抖音和小红书视频，也都是根据http content-type 嗅探的吗
> > 
> > 
> > 都是统一的 浏览器F12看下请求是否走了代理，，看请求头 Remote Address信息
> 
> 我试了下，如果是用mac 下safari浏览器是可以嗅探到的，但是用chrome和firefox浏览器不行，我chrome浏览器是最新版本：126.0.6478.183 (Official Build) (arm64) ，这种有可能是什么原因？

我试了下，如果chrome浏览器开启了无痕浏览模式，又可以嗅探到了

**Comment by putyy** [comment]
> > > > > 这段是根据 http content-type 统一判断资源类型的 晚点试试MAC吧！
> > > > 
> > > > 
> > > > 抖音和小红书视频，也都是根据http content-type 嗅探的吗
> > > 
> > > 
> > > 都是统一的 浏览器F12看下请求是否走了代理，，看请求头 Remote Address信息
> > 
> > 
> > 我试了下，如果是用mac 下safari浏览器是可以嗅探到的，但是用chrome和firefox浏览器不行，我chrome浏览器是最新版本：126.0.6478.183 (Official Build) (arm64) ，这种有可能是什么原因？
> 
> 我试了下，如果chrome浏览器开启了无痕浏览模式，又可以嗅探到了

那估计是你浏览器有某些插件影响了 可以换个浏览器试试
