### ISSUE TITLE
2.0在mac上打不开，覆盖安全性操作，ctrl-打开，安全隐私全开也不行

### ISSUE THREAD

**Issue by alddla** [putyy/res-downloader#54]
<img width="296" alt="image" src="https://github.com/user-attachments/assets/efdb3c34-a42f-46f9-aa23-5bcf5c5168c9">

**Comment by putyy** [comment]
> <img alt="image" width="296" src="https://private-user-images.githubusercontent.com/166582651/350993977-efdb3c34-a42f-46f9-aa23-5bcf5c5168c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTQxNjYsIm5iZiI6MTcyMTY5Mzg2NiwicGF0aCI6Ii8xNjY1ODI2NTEvMzUwOTkzOTc3LWVmZGIzYzM0LWE0MmYtNDZmOS1hYTIzLTViY2Y1YzUxNjhjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMDE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTkxOWM3ZmI2NDEwYTZlNzQ3Y2NiNzBkZTk4MDM5NTQwZjgzMTgwOTU2M2FiYmNkY2QxZWU2NWU3YzNhZjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.57hTAV-eJAn24h3Rx6xjhya9zt3ac3SXrvRjg10j_7A">

由于MAC安全机制引起的，百度 “mac应用程序已损坏无法打开”  处理方法都差不多的，
