### ISSUE TITLE
2.0版本打开之后，一直在这里转圈圈

### ISSUE THREAD

**Issue by kami0314** [putyy/res-downloader#55]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/294dd5d4-e227-492e-948c-4d277b3ee236">

**Comment by kami0314** [comment]
查询8899端口也有，不知道在检测什么，一直loading

**Comment by putyy** [comment]
> 查询8899端口也有，不知道在检测什么，一直loading

loading在启动代理 关闭重启不行？

**Comment by kami0314** [comment]
也不行，重新卸载安装，删除lock文件重新安装证书也不行。

**Comment by kami0314** [comment]
macos版本是12.7.5 (21H1222)，不知道有关系没

**Comment by putyy** [comment]
> macos版本是12.7.5 (21H1222)，不知道有关系没
这个版本没问题 可能要手动debug一下

**Comment by kami0314** [comment]
我通过源码启动之后也是在loading，并且网络这里都是自动代理没有自动勾选上，正常我打开vpn时候这里都是正常的
<img width="1634" alt="image" src="https://github.com/user-attachments/assets/9ebe0323-d918-42b2-8507-790cb5599962">

<img width="751" alt="image" src="https://github.com/user-attachments/assets/f1343bcb-b134-4dee-bcf8-0ecf56bea91a">

**Comment by putyy** [comment]
> 我通过源码启动之后也是在loading，并且网络这里都是自动代理没有自动勾选上，正常我打开vpn时候这里都是正常的 <img alt="image" width="1634" src="https://private-user-images.githubusercontent.com/25736811/352986878-9ebe0323-d918-42b2-8507-790cb5599962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTgyNzksIm5iZiI6MTcyMjQxNzk3OSwicGF0aCI6Ii8yNTczNjgxMS8zNTI5ODY4NzgtOWViZTAzMjMtZDkxOC00MmIyLTg1MDctNzkwY2I1NTk5OTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5MjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNmY3NzU0ZjcxNzFhYWE5NmJiYjhmMjlkYzEzODQ5NWY1ZTAzZTg5MWI1NWYxNWFjMzBiNjZmNmM3MjRkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.br_kqbgdM-oDDQzGjHAjQMv7aJVuUpvUzjZ74ANPO64">
> 
> <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/25736811/352986439-f1343bcb-b134-4dee-bcf8-0ecf56bea91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTgyNzksIm5iZiI6MTcyMjQxNzk3OSwicGF0aCI6Ii8yNTczNjgxMS8zNTI5ODY0MzktZjEzNDNiY2ItYjEzNC00ZGVlLWJjZjgtMGVjZjU2YmVhOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5MjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Y2FkMGIxZTdjMjgzYzQzMWViN2U5ZGM2ZmJiNWMyMWY3NjdiODU0YjYyOGQ0NDFkODA5MTU1ZjIyZTI5NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1LgnyGITah4kQnsxRoQ8kwTyl6ZWXR89fuCPoFLZbI">

那就奇怪 我也有这个系统的MAC 没问题的 你手动调试下呢

**Comment by zhibuyanyanbujin** [comment]
![微信截图_20240810135833](https://github.com/user-attachments/assets/0faf82e2-a1aa-4274-b71c-4fe381683825)
下载的时候图示浏览器不支持video怎么处理，求指导！
