### ISSUE TITLE
开启后无法上网和打开视频。（macos）

### ISSUE THREAD

**Issue by wayhomme** [putyy/res-downloader#56]
<img width="785" alt="image" src="https://github.com/user-attachments/assets/9a9d4d9a-fb54-4b13-a7be-4b1990cfa93c">

一打开软件就无法上网/视频号也无法进入
关闭之后就正常了
感觉是代理的问题，但是不知道如何解决 求！

<img width="477" alt="image" src="https://github.com/user-attachments/assets/7be369db-acd0-459f-ad50-7693593a1e5f">

**Comment by putyy** [comment]
应该是证书没安装好

**Comment by xiefang** [comment]
求 Mac 里正常使用的方法。我的也是这样。但按说明删除 lock 文件重装证书，结果还是一样，打开就上不了网，关掉就正常。

**Comment by putyy** [comment]
软件内代理不要设置

**Comment by zericli090725** [comment]
> 软件内代理不要设置

没有设置代理啊，还是不行

**Comment by izhong** [comment]
2.1.1win版也一样，打开软件就播放不了视频号，跟自己配置fiddler、charles的情况一样。是不是微信那边检测到通过代理就禁止播放啊？

**Comment by zericli090725** [comment]
> 2.1.1win版也一样，打开软件就播放不了视频号，跟自己配置fiddler、charles的情况一样。是不是微信那边检测到通过代理就禁止播放啊？

安装证书就解决了

**Comment by Extreme1206** [comment]
2.1.3win版，同样问题，按说明删除lock，重装证书（自动安装和手动安装都尝试过了）后，开启软件后依然无法上网。软件内也没开启代理
