### ISSUE TITLE
为什么视频预览图没有显示？

### ISSUE THREAD

**Issue by imtiger** [putyy/res-downloader#57]
如图，不管是抖音还是视频号的视频，预览图都没有显示，并且窗口预览也不能播放。
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/0c21ddfa-63ac-4a1f-aad4-ab3010fffdab">

**Comment by putyy** [comment]
> 如图，不管是抖音还是视频号的视频，预览图都没有显示，并且窗口预览也不能播放。 <img alt="image" width="1170" src="https://private-user-images.githubusercontent.com/2855042/352447812-0c21ddfa-63ac-4a1f-aad4-ab3010fffdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDE2MjQsIm5iZiI6MTcyMjAwMTMyNCwicGF0aCI6Ii8yODU1MDQyLzM1MjQ0NzgxMi0wYzIxZGRmYS02M2FjLTRhMWYtYWFkNC1hYjMwMTBmZmZkYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTM0MjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxZDE5ZjIzMDRjNjVhMDUzNDVlYTIxYThiMjg0YTkxNzEyZTgxMzUyMzcxNTVhMmRlYjAwYmM2ZDUwYWUwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DslsWjJ39URbPmB5IHktk5bRg8oMyEim61my9PeDxfg">

抖音窗口预览应该可以 视频号不行 下载能看的，，至于预览图这个没有弄 要适配多平台 感觉没必要

**Comment by imtiger** [comment]
> > 如图，不管是抖音还是视频号的视频，预览图都没有显示，并且窗口预览也不能播放。 <img alt="image" width="1170" src="https://private-user-images.githubusercontent.com/2855042/352447812-0c21ddfa-63ac-4a1f-aad4-ab3010fffdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDE2MjQsIm5iZiI6MTcyMjAwMTMyNCwicGF0aCI6Ii8yODU1MDQyLzM1MjQ0NzgxMi0wYzIxZGRmYS02M2FjLTRhMWYtYWFkNC1hYjMwMTBmZmZkYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTM0MjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxZDE5ZjIzMDRjNjVhMDUzNDVlYTIxYThiMjg0YTkxNzEyZTgxMzUyMzcxNTVhMmRlYjAwYmM2ZDUwYWUwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DslsWjJ39URbPmB5IHktk5bRg8oMyEim61my9PeDxfg">
> 
> 抖音窗口预览应该可以 视频号不行 下载能看的，，至于预览图这个没有弄 要适配多平台 感觉没必要

明白，因为现在视频号打开后可以嗅探出好几个视频，不知道哪个是要下载的，要下载一边才知道，如果有预览图的话，就会方便很多了。

**Comment by putyy** [comment]
> > > 如图，不管是抖音还是视频号的视频，预览图都没有显示，并且窗口预览也不能播放。 <img alt="image" width="1170" src="https://private-user-images.githubusercontent.com/2855042/352447812-0c21ddfa-63ac-4a1f-aad4-ab3010fffdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDE2MjQsIm5iZiI6MTcyMjAwMTMyNCwicGF0aCI6Ii8yODU1MDQyLzM1MjQ0NzgxMi0wYzIxZGRmYS02M2FjLTRhMWYtYWFkNC1hYjMwMTBmZmZkYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTM0MjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxZDE5ZjIzMDRjNjVhMDUzNDVlYTIxYThiMjg0YTkxNzEyZTgxMzUyMzcxNTVhMmRlYjAwYmM2ZDUwYWUwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DslsWjJ39URbPmB5IHktk5bRg8oMyEim61my9PeDxfg">
> > 
> > 
> > 抖音窗口预览应该可以 视频号不行 下载能看的，，至于预览图这个没有弄 要适配多平台 感觉没必要
> 
> 明白，因为现在视频号打开后可以嗅探出好几个视频，不知道哪个是要下载的，要下载一边才知道，如果有预览图的话，就会方便很多了。

dy 可以看一个下一个 sp号有描述
