### ISSUE TITLE
无法嗅探到“未命名”视频号视频的真实地址

### ISSUE THREAD

**Issue by ibob-z** [putyy/res-downloader#58]
putty大神好，昨晚给娃拍了个特效视频(如果你觉得有点累、送你个小地雷、把它扔给你的烦恼、把烦恼都炸飞)，由于从来都没发过视频号，而且一般也不愿意晒孩子，所以发布到自己视频号时并不懂先去添加“描述”、然后再发布，而是直接进行了发布、反手设置了“公开，但不推荐给朋友”，本来想着用您研发的神器回头把视频保存下来就可以了，但没想到今天到了单位在Mac上嗅探不出来，然后我就把res-downloader从1.0.5升级到了2.0，但发现还是只能嗅探出来一个700多KB的错误地址，于是又找了台Windows做测试，发现是一样的情况，但视频边儿上的那些个推荐视频却瞬间就能嗅探出来（即使我都没点播放）。所以我就又做了个测试，自拍了一个同款视频，添加“描述”，发布，嗅探，立马就嗅探出来了。
所以看起来是如果视频号里的视频不存在任何“描述”时，res-downloader可能就无法对嗅探到的视频进行“命名”、才导致了不显示正确地址？
希望能反馈给您参考，如果您觉得有价值的话，未来更新里可以考虑完善。多谢。

**Comment by putyy** [comment]
> putty大神好，昨晚给娃拍了个特效视频(如果你觉得有点累、送你个小地雷、把它扔给你的烦恼、把烦恼都炸飞)，由于从来都没发过视频号，而且一般也不愿意晒孩子，所以发布到自己视频号时并不懂先去添加“描述”、然后再发布，而是直接进行了发布、反手设置了“公开，但不推荐给朋友”，本来想着用您研发的神器回头把视频保存下来就可以了，但没想到今天到了单位在Mac上嗅探不出来，然后我就把res-downloader从1.0.5升级到了2.0，但发现还是只能嗅探出来一个700多KB的错误地址，于是又找了台Windows做测试，发现是一样的情况，但视频边儿上的那些个推荐视频却瞬间就能嗅探出来（即使我都没点播放）。所以我就又做了个测试，自拍了一个同款视频，添加“描述”，发布，嗅探，立马就嗅探出来了。 所以看起来是如果视频号里的视频不存在任何“描述”时，res-downloader可能就无法对嗅探到的视频进行“命名”、才导致了不显示正确地址？ 希望能反馈给您参考，如果您觉得有价值的话，未来更新里可以考虑完善。多谢。

好的 感谢反馈 下个版本修复！
