### ISSUE TITLE
【bug反馈】安装提示程序已损坏

### ISSUE THREAD

**Issue by th10010** [putyy/res-downloader#59]
电脑是Macbook M2芯片，安装新版本程序提示已损坏，请问该如何解决
<img width="167" alt="微信图片_20240729110918" src="https://github.com/user-attachments/assets/76569432-67a4-4e6d-b997-b75e4ba5e63e">

**Comment by putyy** [comment]
#32 可以参考下这个，或者自行百度解决方式都是那几个
比如 https://sysin.org/blog/macos-if-crashes-when-opening/

**Comment by BA7IEE** [comment]
m2芯片遇到同样问题，没能解决，您解决了吗？

**Comment by putyy** [comment]
@BA7IEE #66
