### ISSUE TITLE
请教视频号解码的实现原理

### ISSUE THREAD

**Issue by dada0901** [putyy/res-downloader#63]
希望用 python 重写视频号解码的过程，但是对 node 不熟悉，不理解源代码中是如何集成 WebAssembly 的，是否可以将原生的解密函数集成到 python 中？请教实现思路。

**Comment by putyy** [comment]
> 希望用 python 重写视频号解码的过程，但是对 node 不熟悉，不理解源代码中是如何集成 WebAssembly 的，是否可以将原生的解密函数集成到 python 中？请教实现思路。

本软件并没有直接实现解密算法，直接调用wx 原始js解密的  如果用python去做  可以试着去通过某些模版或其他方式调用原始的js
