### ISSUE TITLE
调用接口解密吗？还是啥？小白在线求解释！

### ISSUE THREAD

**Issue by 08090813** [putyy/res-downloader#64]
莫非视频号解密要走这个接口地址校验才能解密码？

![微信图片_20240809151726](https://github.com/user-attachments/assets/95862c30-f3c3-4cb4-9a94-cd53191a2f9a)
![微信图片_20240809151850](https://github.com/user-attachments/assets/b277b4f5-ccc3-46a5-8bc0-fde5598ae0ba)

没搞懂？求大神解释

**Comment by bingyu88** [comment]
笑死了，都是假开源，也不知道哪来这么多赞。

**Comment by putyy** [comment]
> 莫非视频号解密要走这个接口地址校验才能解密码？
> 
> ![微信图片_20240809151726](https://private-user-images.githubusercontent.com/33471660/356501893-95862c30-f3c3-4cb4-9a94-cd53191a2f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzE1MDcsIm5iZiI6MTcyMzI3MTIwNywicGF0aCI6Ii8zMzQ3MTY2MC8zNTY1MDE4OTMtOTU4NjJjMzAtZjNjMy00Y2I0LTlhOTQtY2Q1MzE5MWEyZjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2MjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZmQzNWYyZWQzYzQzOWY0YmZmZGZhMzEzMTQzNzQzYTllZWM1YzE5MjdmMWI0Yjg2YjM3YWUxOWNjZWNhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7vHPcuOHG7djy8hHGsMQDCyHevtUqEJEjLrPPeWCSg) ![微信图片_20240809151850](https://private-user-images.githubusercontent.com/33471660/356502479-b277b4f5-ccc3-46a5-8bc0-fde5598ae0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzE1MDcsIm5iZiI6MTcyMzI3MTIwNywicGF0aCI6Ii8zMzQ3MTY2MC8zNTY1MDI0NzktYjI3N2I0ZjUtY2NjMy00NmE1LThiYzAtZmRlNTU5OGFlMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2MjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmE3MmIyNWZhNDk1MjgzYmU3NmUzYmEyZTlmMWU2OTNiNGMwMDE0NDEwYWM3ODU4MDI1ODZiZGQyYTk0YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ju3lwhKom3irgfwI95Dlg8jl0aOX67tZwJeWAQGb8pc)
> 
> 没搞懂？求大神解释

这里的接口是随意定的，大概流程：
注入脚本到某些wx js中，通过请求这个路径把需要的数据传给res-downloader进行处理
