### ISSUE TITLE
求助，res-downloader打开后，打开微信视频时就报‘channels.weixin.qq.com 意外终止了连接’

### ISSUE THREAD

**Issue by Aleph-Z** [putyy/res-downloader#65]
证书看着没问题，打开微信视频就ERR_CONNECTION_CLOSED。res-downloader关掉后就正常了
![image](https://github.com/user-attachments/assets/8f8fba30-f44d-4c3a-a5f9-456e7e6f7d40)
![image](https://github.com/user-attachments/assets/68ad2c14-b605-42c6-ab92-a6f9ba81c1a6)

**Comment by putyy** [comment]
检查下系统代理设置 还有就是软件内的设置是什么样的？

**Comment by Aleph-Z** [comment]
也看不出有什么问题来。系统代理设置：
![image](https://github.com/user-attachments/assets/d826facf-a569-4534-a519-1dc3c4d696aa)

软件内的设置是默认的，没动：
![image](https://github.com/user-attachments/assets/c6c32eb5-c2ee-4fa3-a7ca-192586f70a8c)

**Comment by putyy** [comment]
[windows 证书检查以及手动安装过程](https://s.gowas.cn/p/13-ai-xiang-su-cai-xia-zai-qi-xiangxi-anzhuang-zhengshu-guocheng)

@Aleph-Z 按照这个步骤看看

**Comment by Aleph-Z** [comment]
仍然找不出原因，重装后还是不行，证书是对的，防火墙是对的，甚至把防火墙关掉也还是不行

**Comment by putyy** [comment]
浏览器能否拦截？

**Comment by Aleph-Z** [comment]
res-downloader打开后，不止微信视频受影响，浏览器中所有页面都受影响，任何URL都报ERR_CONNECTION_CLOSED

**Comment by xiefang** [comment]
我的 Mac 也是这样，只要打开 res-downloader，微信视频号就是打不开的，一直加载不出来。关掉 res-downloader 软件就正常了。这是什么原因？以前的版本还是正常的。

**Comment by mingzitainanle** [comment]
同上，检查了安装证书都是正确的，在系统的代理设置里面看跟上面的也一样，但是只要软件打开所有浏览器都报连接异常。
![image](https://github.com/user-attachments/assets/839d44b5-3718-4785-b09b-01c806dca174)

**Comment by putyy** [comment]
> 同上，检查了安装证书都是正确的，在系统的代理设置里面看跟上面的也一样，但是只要软件打开所有浏览器都报连接异常。 ![image](https://private-user-images.githubusercontent.com/30645049/359484868-839d44b5-3718-4785-b09b-01c806dca174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjkwOTMsIm5iZiI6MTcyNDIyODc5MywicGF0aCI6Ii8zMDY0NTA0OS8zNTk0ODQ4NjgtODM5ZDQ0YjUtMzcxOC00Nzg1LWIwOWItMDFjODA2ZGNhMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA4MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWNmYjk0NzJmYTY3OTU2NDg0NTllNmY1YWI1ZmE1MTc5YTUyYWNmZWQ3YTgxNjgxZWM3MjUzYTdjMTk3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ANwmUM41YP4EDcLAt-cG4XDzf-hu74Mva1qXLsk-8kA)



> 我的 Mac 也是这样，只要打开 res-downloader，微信视频号就是打不开的，一直加载不出来。关掉 res-downloader 软件就正常了。这是什么原因？以前的版本还是正常的。

软件内的代理设置不要填

**Comment by xiefang** [comment]
> > 同上，检查了安装证书都是正确的，在系统的代理设置里面看跟上面的也一样，但是只要软件打开所有浏览器都报连接异常。 ![image](https://private-user-images.githubusercontent.com/30645049/359484868-839d44b5-3718-4785-b09b-01c806dca174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjkwOTMsIm5iZiI6MTcyNDIyODc5MywicGF0aCI6Ii8zMDY0NTA0OS8zNTk0ODQ4NjgtODM5ZDQ0YjUtMzcxOC00Nzg1LWIwOWItMDFjODA2ZGNhMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA4MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWNmYjk0NzJmYTY3OTU2NDg0NTllNmY1YWI1ZmE1MTc5YTUyYWNmZWQ3YTgxNjgxZWM3MjUzYTdjMTk3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ANwmUM41YP4EDcLAt-cG4XDzf-hu74Mva1qXLsk-8kA)
> 
> > 我的 Mac 也是这样，只要打开 res-downloader，微信视频号就是打不开的，一直加载不出来。关掉 res-downloader 软件就正常了。这是什么原因？以前的版本还是正常的。
> 
> 软件内的代理设置不要填

没填，还是一样的故障。

**Comment by nishilang** [comment]
> > 同上，检查了安装证书都是正确的，在系统的代理设置里面看跟上面的也一样，但是只要软件打开所有浏览器都报连接异常。 ![image](https://private-user-images.githubusercontent.com/30645049/359484868-839d44b5-3718-4785-b09b-01c806dca174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjkwOTMsIm5iZiI6MTcyNDIyODc5MywicGF0aCI6Ii8zMDY0NTA0OS8zNTk0ODQ4NjgtODM5ZDQ0YjUtMzcxOC00Nzg1LWIwOWItMDFjODA2ZGNhMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA4MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWNmYjk0NzJmYTY3OTU2NDg0NTllNmY1YWI1ZmE1MTc5YTUyYWNmZWQ3YTgxNjgxZWM3MjUzYTdjMTk3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ANwmUM41YP4EDcLAt-cG4XDzf-hu74Mva1qXLsk-8kA)
> 
> > 我的 Mac 也是这样，只要打开 res-downloader，微信视频号就是打不开的，一直加载不出来。关掉 res-downloader 软件就正常了。这是什么原因？以前的版本还是正常的。
> 
> 软件内的代理设置不要填

没填   软件内的代理设置，证书也下载导入了，VX视频号  还是无法嗅探

**Comment by putyy** [comment]
@nishilang @xiefang mac通常不会有奇奇怪怪的问题，如果任然无法使用 加群私我吧！

**Comment by Aleph-Z** [comment]
今天安装最新的2.1.1版后没问题了。谢谢！
