### ISSUE TITLE
linux支持

### ISSUE THREAD

**Issue by FriskyFrog** [putyy/res-downloader#68]
希望可以支持linux（确切来说主要是针对[原生linux微信](https://flathub.org/apps/com.tencent.WeChat)的视频号支持) 
感觉整个hub上几乎就找不到有项目支持(可能是这个包比较新没引起太大的关注吧，原生微信tx居然连官网都不放) 
注意到这个项目主要是ts/js写的ele，相比于其他技术栈跨平台应该会相对容易些 
linux用户真的很需要qwq

**Comment by putyy** [comment]
> 希望可以支持linux（确切来说主要是针对[原生linux微信](https://flathub.org/apps/com.tencent.WeChat)的视频号支持) 感觉整个hub上几乎就找不到有项目支持(可能是这个包比较新没引起太大的关注吧，原生微信tx居然连官网都不放) 注意到这个项目主要是ts/js写的ele，相比于其他技术栈跨平台应该会相对容易些 linux用户真的很需要qwq

嗯 这个空了看下

**Comment by putyy** [comment]
@FriskyFrog 可以下载最新版linux的执行文件，手上还没空装linux测下 你方便的话可以先试试
