### ISSUE TITLE
mac上面嗅探不到视频号，软件已经更新

### ISSUE THREAD

**Issue by daishan986** [putyy/res-downloader#69]
![Xnip2024-08-23_](https://github.com/user-attachments/assets/381a00e5-4ff8-4713-9e08-0cc2d3fa8520)
![Xnip2024-08-23_1](https://github.com/user-attachments/assets/c8bff021-fdb0-48b1-927e-1a4875a32352)

**Comment by putyy** [comment]
> ![Xnip2024-08-23_](https://private-user-images.githubusercontent.com/179194095/360788952-381a00e5-4ff8-4713-9e08-0cc2d3fa8520.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTI4NjEsIm5iZiI6MTcyNDM5MjU2MSwicGF0aCI6Ii8xNzkxOTQwOTUvMzYwNzg4OTUyLTM4MWEwMGU1LTRmZjgtNDcxMy05ZTA4LTBjYzJkM2ZhODUyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNTU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWFhMGY4Y2I1NWYzM2Q4ODE2MzhmZTUwMmViZTk0YzAyMmI5OTE0OTAwZGUwNDAwM2QyNTIwZTM5YWRkZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pxkYhKRLt_M0llMKO-FWqpVxD6KkDLPBd3wp9ns5SL4) ![Xnip2024-08-23_1](https://private-user-images.githubusercontent.com/179194095/360788962-c8bff021-fdb0-48b1-927e-1a4875a32352.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTI4NjEsIm5iZiI6MTcyNDM5MjU2MSwicGF0aCI6Ii8xNzkxOTQwOTUvMzYwNzg4OTYyLWM4YmZmMDIxLWZkYjAtNDhiMS05MjdlLTFhNDg3NWEzMjM1Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNTU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTRhZWZiNWEwMGI0MWYzZmU4YjhjMTUxMzc5YmMzNzFjYTQwYTM2YzNmMmQ4MDZjYThjNWVhODhiNjk4YjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s8Jbojd8sJwYsoxH-PQ32vNWx2G9CJmo1mLKZ5iITl4)

代理服务不要设置
