### ISSUE TITLE
Do not see video on software 

### ISSUE THREAD

**Issue by emourdavid** [putyy/res-downloader#72]
![image](https://github.com/user-attachments/assets/477be344-8d25-4bc3-9326-1d8fc5440e42)

![image](https://github.com/user-attachments/assets/759e80f1-cac9-4a23-8962-6b55ba5dcfd2)

![image](https://github.com/user-attachments/assets/68bdd280-488c-4daa-a9fe-1014f1487a3d)

![image](https://github.com/user-attachments/assets/d2e927e8-73f6-4351-8fc5-aece5173f067)

I setup settings like above screenshots but do not see any video on software. Would you please help why?

**Comment by putyy** [comment]
No need to set up a proxy in the software.
