### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by nasa2046** [putyy/res-downloader#74]
用软件嗅探了视频号，点击“解密下载”后报这个错误。

TypeError: Cannot read properties of undefined (reading 'length')
    at Zi.calculateDownloadProgress (C:\Users\Administrator\AppData\Local\Programs\res-downloader\resources\app.asar\dist-electron\main\index.js:38:12769)
    at C:\Users\Administrator\AppData\Local\Programs\res-downloader\resources\app.asar\dist-electron\main\index.js:38:14721
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

另外，证书在哪儿安装呢？我安装好了软件之后，并没有提示我安装证书。

**Comment by putyy** [comment]
> 用软件嗅探了视频号，点击“解密下载”后报这个错误。
> 
> TypeError: Cannot read properties of undefined (reading 'length') at Zi.calculateDownloadProgress (C:\Users\Administrator\AppData\Local\Programs\res-downloader\resources\app.asar\dist-electron\main\index.js:38:12769) at C:\Users\Administrator\AppData\Local\Programs\res-downloader\resources\app.asar\dist-electron\main\index.js:38:14721 at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 另外，证书在哪儿安装呢？我安装好了软件之后，并没有提示我安装证书。

安装最新的吗？ 2.1.1
