### ISSUE TITLE
开发环境下点击微信视频号下载按钮报错

### ISSUE THREAD

**Issue by 2976151305** [putyy/res-downloader#76]
开发环境时点击下载按钮报错，信息如下
```
err: AxiosError: connect ECONNREFUSED 127.0.0.1:18899
    at Function.AxiosError.from (/res-downloader/node_modules/_axios@1.7.7@axios/lib/core/AxiosError.js:92:14)
    at RedirectableRequest.handleRequestError (/res-downloader/node_modules/_axios@1.7.7@axios/lib/adapters/http.js:620:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/res-downloader/node_modules/_follow-redirects@1.15.6@follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/res-downloader/node_modules/_axios@1.7.7@axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  port: 18899,
  address: '127.0.0.1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -61,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.7.7',
      'Content-Length': '1214',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://127.0.0.1:18899/jsonrpc',
    data: '{"jsonrpc":"2.0","method":"aria2.addUri","params":[["https://finder.video.qq.com/251/20302/stodownload?encfilekey=6xykWLEnztKcKCJZcV0rWCM8ua7DibZkibPSZaIgeFjxHbZSK3ufial8ibHL0b8acuEfwicHPzIDnzeibpjW6giaR6LyyZpYP4oLT3OEUwpcOKb6ib4TQe2d0rwGSyBxuibZT6qZ9j557lJMVT3tayC3QsdRKdiaobmh0icsrnVjtqDQyWspkY&a=1&bizid=1023&dotrans=0&hy=SZ&idx=1&m=ace804cd5199fcf7bc62925cf470888b&upid=290150&web=1&token=o3K9JoTic9IiacjbicPDpEkm8icicmYnHrcxMvUhRAkKQsyyoDmeByF0ibNbJFyeuytFBN8ib6ndNfHIu0369e3SaXhFUnfexC90IbJ6EJmsD1ckibiaib0cFSibpmu8A&ctsc=143&extg=10f0000&svrbypass=AAuL%2FQsFAAABAAAAAABxGJQZilH9U8MrhHjdZhAAAADnaHZTnGbFfAj9RgZXfw6VONSxzbCvgUH4AU6VRoacx5OkPcGkDSc9PpX%2B%2FxPgtJshGRMLE4SScm8%3D&svrnonce=1725790340&X-snsvideoflag=xWT158"],{"dir":"/Users/huangzhenhong/Downloads","out":"没结婚的想结婚结了婚的后悔吗长大后才知道女孩子是没有家的跟蒲公英一样落到肥处迎风长落到瘦处苦一生结婚不是救赎家也不是避风港只有自己才是自己的救赎自己才是自己的避风港婚姻女人家庭_20240908181250.mp4","headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"}}],"id":30}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/jsonrpc',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '127.0.0.1',
      port: '18899',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/jsonrpc'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 1214,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '1214',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /jsonrpc HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.7.7\r\n' +
        'Content-Length: 1214\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 127.0.0.1:18899\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/jsonrpc',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://127.0.0.1:18899/jsonrpc',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 127.0.0.1:18899
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 18899
  }
}
```

**Comment by putyy** [comment]
> 开发环境时点击下载按钮报错，信息如下
> 
> ```
> err: AxiosError: connect ECONNREFUSED 127.0.0.1:18899
>     at Function.AxiosError.from (/res-downloader/node_modules/_axios@1.7.7@axios/lib/core/AxiosError.js:92:14)
>     at RedirectableRequest.handleRequestError (/res-downloader/node_modules/_axios@1.7.7@axios/lib/adapters/http.js:620:25)
>     at RedirectableRequest.emit (node:events:513:28)
>     at ClientRequest.eventHandlers.<computed> (/res-downloader/node_modules/_follow-redirects@1.15.6@follow-redirects/index.js:38:24)
>     at ClientRequest.emit (node:events:513:28)
>     at Socket.socketErrorListener (node:_http_client:502:9)
>     at Socket.emit (node:events:513:28)
>     at emitErrorNT (node:internal/streams/destroy:151:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21)
>     at Axios.request (/res-downloader/node_modules/_axios@1.7.7@axios/lib/core/Axios.js:45:41)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   port: 18899,
>   address: '127.0.0.1',
>   syscall: 'connect',
>   code: 'ECONNREFUSED',
>   errno: -61,
>   config: {
>     transitional: {
>       silentJSONParsing: true,
>       forcedJSONParsing: true,
>       clarifyTimeoutError: false
>     },
>     adapter: [ 'xhr', 'http', 'fetch' ],
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     timeout: 0,
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,
>     maxBodyLength: -1,
>     env: { FormData: [Function], Blob: [class Blob] },
>     validateStatus: [Function: validateStatus],
>     headers: Object [AxiosHeaders] {
>       Accept: 'application/json, text/plain, */*',
>       'Content-Type': 'application/json',
>       'User-Agent': 'axios/1.7.7',
>       'Content-Length': '1214',
>       'Accept-Encoding': 'gzip, compress, deflate, br'
>     },
>     method: 'post',
>     url: 'http://127.0.0.1:18899/jsonrpc',
>     data: '{"jsonrpc":"2.0","method":"aria2.addUri","params":[["https://finder.video.qq.com/251/20302/stodownload?encfilekey=6xykWLEnztKcKCJZcV0rWCM8ua7DibZkibPSZaIgeFjxHbZSK3ufial8ibHL0b8acuEfwicHPzIDnzeibpjW6giaR6LyyZpYP4oLT3OEUwpcOKb6ib4TQe2d0rwGSyBxuibZT6qZ9j557lJMVT3tayC3QsdRKdiaobmh0icsrnVjtqDQyWspkY&a=1&bizid=1023&dotrans=0&hy=SZ&idx=1&m=ace804cd5199fcf7bc62925cf470888b&upid=290150&web=1&token=o3K9JoTic9IiacjbicPDpEkm8icicmYnHrcxMvUhRAkKQsyyoDmeByF0ibNbJFyeuytFBN8ib6ndNfHIu0369e3SaXhFUnfexC90IbJ6EJmsD1ckibiaib0cFSibpmu8A&ctsc=143&extg=10f0000&svrbypass=AAuL%2FQsFAAABAAAAAABxGJQZilH9U8MrhHjdZhAAAADnaHZTnGbFfAj9RgZXfw6VONSxzbCvgUH4AU6VRoacx5OkPcGkDSc9PpX%2B%2FxPgtJshGRMLE4SScm8%3D&svrnonce=1725790340&X-snsvideoflag=xWT158"],{"dir":"/Users/huangzhenhong/Downloads","out":"没结婚的想结婚结了婚的后悔吗长大后才知道女孩子是没有家的跟蒲公英一样落到肥处迎风长落到瘦处苦一生结婚不是救赎家也不是避风港只有自己才是自己的救赎自己才是自己的避风港婚姻女人家庭_20240908181250.mp4","headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"}}],"id":30}'
>   },
>   request: <ref *1> Writable {
>     _writableState: WritableState {
>       objectMode: false,
>       highWaterMark: 16384,
>       finalCalled: false,
>       needDrain: false,
>       ending: false,
>       ended: false,
>       finished: false,
>       destroyed: false,
>       decodeStrings: true,
>       defaultEncoding: 'utf8',
>       length: 0,
>       writing: false,
>       corked: 0,
>       sync: true,
>       bufferProcessing: false,
>       onwrite: [Function: bound onwrite],
>       writecb: null,
>       writelen: 0,
>       afterWriteTickInfo: null,
>       buffered: [],
>       bufferedIndex: 0,
>       allBuffers: true,
>       allNoop: true,
>       pendingcb: 0,
>       constructed: true,
>       prefinished: false,
>       errorEmitted: false,
>       emitClose: true,
>       autoDestroy: true,
>       errored: null,
>       closed: false,
>       closeEmitted: false,
>       [Symbol(kOnFinished)]: []
>     },
>     _events: [Object: null prototype] {
>       response: [Function: handleResponse],
>       error: [Function: handleRequestError],
>       socket: [Function: handleRequestSocket]
>     },
>     _eventsCount: 3,
>     _maxListeners: undefined,
>     _options: {
>       maxRedirects: 21,
>       maxBodyLength: Infinity,
>       protocol: 'http:',
>       path: '/jsonrpc',
>       method: 'POST',
>       headers: [Object: null prototype],
>       agents: [Object],
>       auth: undefined,
>       family: undefined,
>       beforeRedirect: [Function: dispatchBeforeRedirect],
>       beforeRedirects: [Object],
>       hostname: '127.0.0.1',
>       port: '18899',
>       agent: undefined,
>       nativeProtocols: [Object],
>       pathname: '/jsonrpc'
>     },
>     _ended: false,
>     _ending: true,
>     _redirectCount: 0,
>     _redirects: [],
>     _requestBodyLength: 1214,
>     _requestBodyBuffers: [ [Object] ],
>     _onNativeResponse: [Function (anonymous)],
>     _currentRequest: ClientRequest {
>       _events: [Object: null prototype],
>       _eventsCount: 7,
>       _maxListeners: undefined,
>       outputData: [],
>       outputSize: 0,
>       writable: true,
>       destroyed: false,
>       _last: true,
>       chunkedEncoding: false,
>       shouldKeepAlive: false,
>       maxRequestsOnConnectionReached: false,
>       _defaultKeepAlive: true,
>       useChunkedEncodingByDefault: true,
>       sendDate: false,
>       _removedConnection: false,
>       _removedContLen: false,
>       _removedTE: false,
>       strictContentLength: false,
>       _contentLength: '1214',
>       _hasBody: true,
>       _trailer: '',
>       finished: false,
>       _headerSent: true,
>       _closed: false,
>       socket: [Socket],
>       _header: 'POST /jsonrpc HTTP/1.1\r\n' +
>         'Accept: application/json, text/plain, */*\r\n' +
>         'Content-Type: application/json\r\n' +
>         'User-Agent: axios/1.7.7\r\n' +
>         'Content-Length: 1214\r\n' +
>         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
>         'Host: 127.0.0.1:18899\r\n' +
>         'Connection: close\r\n' +
>         '\r\n',
>       _keepAliveTimeout: 0,
>       _onPendingData: [Function: nop],
>       agent: [Agent],
>       socketPath: undefined,
>       method: 'POST',
>       maxHeaderSize: undefined,
>       insecureHTTPParser: undefined,
>       joinDuplicateHeaders: undefined,
>       path: '/jsonrpc',
>       _ended: false,
>       res: null,
>       aborted: false,
>       timeoutCb: null,
>       upgradeOrConnect: false,
>       parser: null,
>       maxHeadersCount: null,
>       reusedSocket: false,
>       host: '127.0.0.1',
>       protocol: 'http:',
>       _redirectable: [Circular *1],
>       [Symbol(kCapture)]: false,
>       [Symbol(kBytesWritten)]: 0,
>       [Symbol(kNeedDrain)]: false,
>       [Symbol(corked)]: 0,
>       [Symbol(kOutHeaders)]: [Object: null prototype],
>       [Symbol(errored)]: null,
>       [Symbol(kUniqueHeaders)]: null
>     },
>     _currentUrl: 'http://127.0.0.1:18899/jsonrpc',
>     [Symbol(kCapture)]: false
>   },
>   cause: Error: connect ECONNREFUSED 127.0.0.1:18899
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
>     errno: -61,
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '127.0.0.1',
>     port: 18899
>   }
> }
> ```

代码拉取最新的
