### ISSUE TITLE
软件打开一直loding

### ISSUE THREAD

**Issue by chaoweimt** [putyy/res-downloader#78]
软件一直loading

**Comment by chaoweimt** [comment]
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/dea29643-6bd5-4ab3-a4fa-95d25dba9060">

**Comment by chaoweimt** [comment]
使用的是macos x86_64 系统

**Comment by putyy** [comment]
@chaoweimt #73 参考这个命令行运行排查下
