### ISSUE TITLE
视频号下载无法播放问题，临时解决方案

### ISSUE THREAD

**Issue by putyy** [putyy/res-downloader#8]
官方又做了改动，临时解决方式 可以通过“搜一搜”找到要下载的视频 进行拦截下载

#10 #7 #6

**Comment by macyoyo** [comment]
搜一搜方式可以用，只不过的通过预览页直接开始播放，才能获取到能下载的视频。

**Comment by bobo-gh** [comment]
视频加密，不能播放了！

**Comment by putyy** [comment]
@bobo-gh 已更新！

**Comment by songyunbiao** [comment]
> @bobo-gh 已更新！

还是不能解密，不能播放。
![1704264152874](https://github.com/putyy/res-downloader/assets/9216385/3806ab56-59a7-48c1-93b6-a272e026869c)

**Comment by putyy** [comment]
> > @bobo-gh 已更新！
> 
> 还是不能解密，不能播放。 ![WX20240103-144341@2x](https://private-user-images.githubusercontent.com/9216385/293848197-71677501-2afa-4af1-8791-ca9c803c90ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjQ2NzcsIm5iZiI6MTcwNDI2NDM3NywicGF0aCI6Ii85MjE2Mzg1LzI5Mzg0ODE5Ny03MTY3NzUwMS0yYWZhLTRhZjEtODc5MS1jYTljODAzYzkwZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDY0NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM4OTlhYTExNDc1NTM0YTg2NjA3ZWVlZGY2YjIyN2UwZjRlMTg4YjEyNGJkY2IwMjViNTdiMmVjM2FjNWE1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f6j5gvUPo0Ml6uidRa9rId15cW6xQE7Vnmzi-KHD15U)

点一个:   解密下载  就可以

**Comment by songyunbiao** [comment]
> > > @bobo-gh 已更新！
> > 
> > 
> > 还是不能解密，不能播放。 ![WX20240103-144341@2x](https://private-user-images.githubusercontent.com/9216385/293848197-71677501-2afa-4af1-8791-ca9c803c90ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjQ2NzcsIm5iZiI6MTcwNDI2NDM3NywicGF0aCI6Ii85MjE2Mzg1LzI5Mzg0ODE5Ny03MTY3NzUwMS0yYWZhLTRhZjEtODc5MS1jYTljODAzYzkwZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDY0NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM4OTlhYTExNDc1NTM0YTg2NjA3ZWVlZGY2YjIyN2UwZjRlMTg4YjEyNGJkY2IwMjViNTdiMmVjM2FjNWE1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f6j5gvUPo0Ml6uidRa9rId15cW6xQE7Vnmzi-KHD15U)
> 
> 点一个: 解密下载 就可以

大多数没有解密按钮，能下载，下载下来不能播放，不知道大佬那里能重现不。

**Comment by songyunbiao** [comment]
![1704265308069](https://github.com/putyy/res-downloader/assets/9216385/9388a002-d7cd-46f0-b9e1-a563863ed9f0)
![WX20240103-150220@2x](https://github.com/putyy/res-downloader/assets/9216385/aa1920e4-a29f-42de-a1dd-db11a5df397c)

**Comment by putyy** [comment]
> > > > @bobo-gh 已更新！
> > > 
> > > 
> > > 还是不能解密，不能播放。 ![WX20240103-144341@2x](https://private-user-images.githubusercontent.com/9216385/293848197-71677501-2afa-4af1-8791-ca9c803c90ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjQ2NzcsIm5iZiI6MTcwNDI2NDM3NywicGF0aCI6Ii85MjE2Mzg1LzI5Mzg0ODE5Ny03MTY3NzUwMS0yYWZhLTRhZjEtODc5MS1jYTljODAzYzkwZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMDY0NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM4OTlhYTExNDc1NTM0YTg2NjA3ZWVlZGY2YjIyN2UwZjRlMTg4YjEyNGJkY2IwMjViNTdiMmVjM2FjNWE1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f6j5gvUPo0Ml6uidRa9rId15cW6xQE7Vnmzi-KHD15U)
> > 
> > 
> > 点一个: 解密下载 就可以
> 
> 大多数没有解密按钮，能下载，下载下来不能播放，不知道大佬那里能重现不。

嗯嗯  如果是视频号 只有显示了解密下载的下载下来才能播放 其他的不行，操作流程是这样的：把要下载的视频发到文件助手或好友  再打开这个分享的视频  就能看到解密下载了

**Comment by putyy** [comment]
没有显示解密下载的视频号视频 和之前的一样 没有做拦截 还是会显示在软件界面，上面说的方式操作会显示解密下载 并且视频下面会显示视频的描述

**Comment by songyunbiao** [comment]
> 没有显示解密下载的视频号视频 和之前的一样 没有做拦截 还是会显示在软件界面，上面说的方式操作会显示解密下载 并且视频下面会显示视频的描述

感谢大佬，这样确实可以下载了。提个小小的建议，能不能下载的时候，有一个下载进度显示，不然视频稍微大一点，一直在那里转，也不知道下载到什么程度了。

**Comment by songyunbiao** [comment]
![WX20240103-163413@2x](https://github.com/putyy/res-downloader/assets/9216385/a97bc8d8-7b39-4ab0-bd87-50e5358f0e99)

**Comment by putyy** [comment]
> > 没有显示解密下载的视频号视频 和之前的一样 没有做拦截 还是会显示在软件界面，上面说的方式操作会显示解密下载 并且视频下面会显示视频的描述
> 
> 感谢大佬，这样确实可以下载了。提个小小的建议，能不能下载的时候，有一个下载进度显示，不然视频稍微大一点，一直在那里转，也不知道下载到什么程度了。

ok

**Comment by kaoson** [comment]
mac下一点用都没有，显示"No Data"

**Comment by putyy** [comment]
> mac下一点用都没有，显示"No Data"

我这边mac可以哦 你可以手动检查下代理
