### ISSUE TITLE
mac OS 安装之后一直在loading 我该如何是好？

### ISSUE THREAD

**Issue by timkim2021** [putyy/res-downloader#82]
<img width="792" alt="image" src="https://github.com/user-attachments/assets/4652a21b-611c-4cf9-a699-f4c565b7f396">
macOS big sur 版本  安装之后一直在loading 我该如何是好？

**Comment by timkim2021** [comment]
设置 - 安全与隐私 - 防火墙 - 防火墙选项 - res-downloader 设置为允许传入连接
WiFi设置 代理连接 - 127.0.0.1 端口8899 已设置好。
但是还是一直在loading 抓取视频是貌似可以了但是画面还是在黑屏。
![QQ_1727325672460](https://github.com/user-attachments/assets/68b74bac-9b7d-4c7f-b9dd-c8395a4c8231)

**Comment by putyy** [comment]
> 设置 - 安全与隐私 - 防火墙 - 防火墙选项 - res-downloader 设置为允许传入连接 WiFi设置 代理连接 - 127.0.0.1 端口8899 已设置好。 但是还是一直在loading 抓取视频是貌似可以了但是画面还是在黑屏。 ![QQ_1727325672460](https://private-user-images.githubusercontent.com/41264655/370986889-68b74bac-9b7d-4c7f-b9dd-c8395a4c8231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTk5MjAsIm5iZiI6MTcyNzM5OTYyMCwicGF0aCI6Ii80MTI2NDY1NS8zNzA5ODY4ODktNjhiNzRiYWMtOWI3ZC00YzdmLWI5ZGQtYzgzOTVhNGM4MjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAxMTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMmRmZjNmNTIzYmFmNTRhNzdhN2QwODIwOGMxMTNhZWFkYjUwM2IzODA0YzA0YTFhNjVmMzliMjM2ZTg3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lwxK9yCLKwvL_Iv_tn4PFdq0JiiAh-v2bb5Rz1GIR3M)

这个在设置代理 但是我没这个版本的Mac 不太清楚哪一步卡住了
