### ISSUE TITLE
近期视频号无法抓取了

### ISSUE THREAD

**Issue by xiaomingzzzzz** [putyy/res-downloader#83]
RT 辛苦大佬看看

**Comment by putyy** [comment]
> RT 辛苦大佬看看

2.1.1能正常使用哦

**Comment by abandon17** [comment]
我的更新了还是不行！2.1.1

**Comment by abandon17** [comment]
请问下为啥我的2.1.1解密下载还是卡在0%

**Comment by putyy** [comment]
> > > RT 辛苦大佬看看
> > 
> > 
> > 2.1.1能正常使用哦
> 
> 感谢大佬 确实可以了，想问问里面选视频号画质具体咋搞的，可以理解为视频号有三种分发策略，虽然前端不能选择但是在res上可选吗

测试下来默认就是最高清的  其他的是res里面拦截到的

**Comment by neohob** [comment]
mac 版本嗅探不成功，9.20 还能用

**Comment by aben1900** [comment]
2024年11月21日，win11版本，不能嗅探了，视频号也没反应。

**Comment by xiaomingzzzzz** [comment]
目前小红书和视频号都嗅探不到了（听说小红书也是用的tx的防爬方案）

**Comment by xiaomingzzzzz** [comment]
win10，已经更新到2.2.0版本了

**Comment by skysunsun** [comment]
目前11.27 视频号不行了，win10，版本2.2。0
