### ISSUE TITLE
视频号视频下载失败

### ISSUE THREAD

**Issue by hehec123** [putyy/res-downloader#84]
请教大佬个问题：

**Comment by hehec123** [comment]
不好意思一不小心发出去了
问题1：软件启动完毕后，loading后出现主程序界面，会提示“Error: Error invoking remote method 'invoke_start_proxy': setting proxy err: Error: vbscript process reported unknown error code 1”，目前看这个错误好像不影响使用
问题2：目前软件能够嗅探视频号的视频，并且能够正常预览，但是点击下载会提示下载失败，目前只能将url拷贝出来在浏览器中下载

**Comment by hehec123** [comment]
![下载失败](https://github.com/user-attachments/assets/04969f0c-5deb-4418-80c9-b01cbc61a362)
上面是错误提示，我的操作系统是win10

**Comment by putyy** [comment]
> ![下载失败](https://private-user-images.githubusercontent.com/35129256/371448934-04969f0c-5deb-4418-80c9-b01cbc61a362.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjUyODAsIm5iZiI6MTcyNzQyNDk4MCwicGF0aCI6Ii8zNTEyOTI1Ni8zNzE0NDg5MzQtMDQ5NjlmMGMtNWRlYi00NDE4LTgwYzktYjAxY2JjNjFhMzYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4MTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMGU0MTNjMTYwNWY5ZDZkMWY5ZWM3NWQxMmQwMGY4OTRmOGVlZTFjN2I4MDlmZGU2MzI5NzUwODZlNzE2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H_tzh5ibo0yw4UJoD6rdtA70HvXo3gFJVWPmUBj1Na4) 上面是错误提示，我的操作系统是win10

最新版？

**Comment by hehec123** [comment]
> > ![下载失败](https://private-user-images.githubusercontent.com/35129256/371448934-04969f0c-5deb-4418-80c9-b01cbc61a362.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjUyODAsIm5iZiI6MTcyNzQyNDk4MCwicGF0aCI6Ii8zNTEyOTI1Ni8zNzE0NDg5MzQtMDQ5NjlmMGMtNWRlYi00NDE4LTgwYzktYjAxY2JjNjFhMzYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4MTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMGU0MTNjMTYwNWY5ZDZkMWY5ZWM3NWQxMmQwMGY4OTRmOGVlZTFjN2I4MDlmZGU2MzI5NzUwODZlNzE2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H_tzh5ibo0yw4UJoD6rdtA70HvXo3gFJVWPmUBj1Na4) 上面是错误提示，我的操作系统是win10
> 
> 最新版？

不好意思，忘了说版本号了，我用的2.1.1，应该是最新版
