### ISSUE TITLE
设置了目录但是无论批量还是单独下载还是不断重复设置目录提示

### ISSUE THREAD

**Issue by NB-player** [putyy/res-downloader#86]
尝试过重装，也尝试过卸载后彻底清除目录 2.1.1版本
![1728135644397](https://github.com/user-attachments/assets/2d76dc8b-0492-4998-997a-0fa57ecd0bfa)
![image](https://github.com/user-attachments/assets/5eb32876-b067-4267-89d9-d30909d042a4)

**Comment by putyy** [comment]
> NB-player

点下保存
