### ISSUE TITLE
mac系统安装后，一直卡在“laoding”

### ISSUE THREAD

**Issue by th10010** [putyy/res-downloader#88]
如图所示，我是mac系统，安装的arm64版本，安装后在使用过程中一直卡在loading界面上，请求解决办法。
![333](https://github.com/user-attachments/assets/3f99228b-0fff-4f14-9396-420a0ec3967c)

**Comment by putyy** [comment]
@th10010 loading在执行启动代理 可能哪里卡住了 命令行执行看看，或者重启电脑再试

**Comment by th10010** [comment]
> @th10010 loading在执行启动代理 可能哪里卡住了 命令行执行看看，或者重启电脑再试

请问命令行怎么执行呢？重启过了没用
