### ISSUE TITLE
windows11 24H2 代理失败

### ISSUE THREAD

**Issue by wybb** [putyy/res-downloader#98]
启动后系统代理状态正常，但是只能打开http网站，https打开是失败的
![https网站](https://github.com/user-attachments/assets/d8eccf0d-aed0-4a58-ba25-83d7df86c425)
![http网站](https://github.com/user-attachments/assets/32e040af-9794-48eb-aa6b-df914b35ba4d)

查看证书，已经正确加入“受信任的根证书颁发机构”，即使手工删掉证书和.res-downloader@putyy，重新添加也依然无效
![证书状态](https://github.com/user-attachments/assets/c1f76976-ddf6-4b88-92d2-02c6ab0dde76)

而相同系统中的fiddler 添加证书后 https解密功能是完全正常的
![fiddler](https://github.com/user-attachments/assets/5135fefb-96f6-4bc1-bafc-644fe557aebd)

**Comment by putyy** [comment]
有朋友反馈 win11 24H2版本需关闭 bbr2功能

**Comment by Asice** [comment]
win11好像都有这个问题，win10就没问题
